# Generated by Django 3.2 on 2021-04-26 11:56

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('acquisition_type', models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('close_landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, choices=[('Hostel', 'Hostel'), ('Flat', 'Flat'), ('Apartment', 'Apartment'), ('Self-Contained', 'Self-Contained')], max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_furnished', models.BooleanField(blank=True, default=False, null=True)),
                ('number_of_bedrooms', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_washrooms', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_kitchen', models.IntegerField(blank=True, default=0, null=True)),
                ('has_compound', models.IntegerField(blank=True, default=0, null=True)),
                ('for_sale_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('for_rent_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, choices=[(1, 'Available'), (0, 'Unavailable')], max_length=250, null=True)),
                ('rent_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('listed_by', models.CharField(blank=True, choices=[('Agency', 'Agency'), ('Owner', 'Owner'), ('Agent', 'Agent')], max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'house',
                'ordering': ['created_by__is_star', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'page_visits',
                'ordering': ['created_at'],
            },
        ),
    ]
