# Generated by Django 3.2 on 2021-04-26 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='garage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, choices=[('Hostel', 'Hostel'), ('Flat', 'Flat'), ('Self-Contained', 'Self-Contained'), ('Apartment', 'Apartment')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='house',
            name='listed_by',
            field=models.CharField(blank=True, choices=[('Agent', 'Agent'), ('Owner', 'Owner'), ('Agency', 'Agency')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Unavailable'), (1, 'Available')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='properties/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_image',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='house',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='house_images', to='estate.PropertyImage'),
        ),
    ]
