# Generated by Django 3.2 on 2021-04-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_auto_20210426_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='acquisition_type',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, choices=[('Flat', 'Flat'), ('Apartment', 'Apartment'), ('Self-Contained', 'Self-Contained'), ('Hostel', 'Hostel')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='listed_by',
            field=models.CharField(blank=True, choices=[('Agent', 'Agent'), ('Agency', 'Agency'), ('Owner', 'Owner')], max_length=250, null=True),
        ),
    ]
