# Generated by Django 3.2 on 2021-04-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_auto_20210426_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='location',
            new_name='region',
        ),
        migrations.AddField(
            model_name='house',
            name='town',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, choices=[('Hostel', 'Hostel'), ('Apartment', 'Apartment'), ('Flat', 'Flat'), ('Self-Contained', 'Self-Contained')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='listed_by',
            field=models.CharField(blank=True, choices=[('Agency', 'Agency'), ('Agent', 'Agent'), ('Owner', 'Owner')], max_length=250, null=True),
        ),
    ]
