# Generated by Django 3.2 on 2021-04-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_auto_20210427_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, choices=[('Hostel', 'Hostel'), ('Self-Contained', 'Self-Contained'), ('Apartment', 'Apartment'), ('Flat', 'Flat')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='listed_by',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Agency', 'Agency'), ('Agent', 'Agent')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(blank=True, choices=[(1, 'Available'), (0, 'Unavailable')], max_length=250, null=True),
        ),
    ]
