# Generated by Django 3.2 on 2021-05-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0009_auto_20210430_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='garage',
        ),
        migrations.AddField(
            model_name='house',
            name='has_garage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, choices=[('Self-Contained', 'Self-Contained'), ('Apartment', 'Apartment'), ('Hostel', 'Hostel'), ('Flat', 'Flat')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='listed_by',
            field=models.CharField(blank=True, choices=[('Agency', 'Agency'), ('Owner', 'Owner'), ('Agent', 'Agent')], max_length=250, null=True),
        ),
    ]
