# Generated by Django 3.2 on 2021-05-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0011_auto_20210504_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Self-Contained', 'Self-Contained'), ('Hostel', 'Hostel'), ('Flat', 'Flat')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='rent_duration',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
