# Generated by Django 3.2 on 2021-05-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0012_auto_20210505_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='acquisition_type',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, choices=[('Self-Contained', 'Self-Contained'), ('Flat', 'Flat'), ('Apartment', 'Apartment'), ('Hostel', 'Hostel')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='rent_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Unavailable'), (1, 'Available')], null=True),
        ),
    ]
