# Generated by Django 3.2 on 2021-05-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0013_auto_20210505_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='page_views',
            field=models.ManyToManyField(blank=True, null=True, related_name='house_views', to='estate.PageVisit'),
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, choices=[('Flat', 'Flat'), ('Hostel', 'Hostel'), ('Apartment', 'Apartment'), ('Self-Contained', 'Self-Contained')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='listed_by',
            field=models.CharField(blank=True, choices=[('Agency', 'Agency'), ('Owner', 'Owner'), ('Agent', 'Agent')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Available'), (0, 'Unavailable')], null=True),
        ),
    ]
