# Generated by Django 3.2 on 2021-05-19 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate', '0016_auto_20210510_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='acquisition_type',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Self-Contained', 'Self-Contained'), ('Flat', 'Flat'), ('Hostel', 'Hostel')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='listed_by',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Agency', 'Agency'), ('Agent', 'Agent')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='region',
            field=models.CharField(blank=True, choices=[('Northen', 'Northen'), ('Eastern', 'Eastern'), ('Greater Accra', 'Greater Accra'), ('Western', 'Western'), ('Ashanti', 'Ashanti')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='towns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Town',
                'verbose_name_plural': 'Towns',
                'db_table': 'town',
                'managed': True,
            },
        ),
    ]
