# Generated by Django 3.2 on 2021-05-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0017_auto_20210519_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, choices=[('Hostel', 'Hostel'), ('Flat', 'Flat'), ('Self-Contained', 'Self-Contained'), ('Apartment', 'Apartment')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='listed_by',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Agent', 'Agent'), ('Agency', 'Agency')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='region',
            field=models.CharField(blank=True, choices=[('Eastern', 'Eastern'), ('Western', 'Western'), ('Ashanti', 'Ashanti'), ('Northern', 'Northern'), ('Greater Accra', 'Greater Accra')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Unavailable'), (1, 'Available')], null=True),
        ),
    ]
