# Generated by Django 3.2 on 2021-05-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0018_auto_20210531_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, choices=[('Self-Contained', 'Self-Contained'), ('Flat', 'Flat'), ('Apartment', 'Apartment'), ('Hostel', 'Hostel')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='listed_by',
            field=models.CharField(blank=True, choices=[('Agent', 'Agent'), ('Owner', 'Owner'), ('Agency', 'Agency')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='region',
            field=models.CharField(blank=True, choices=[('Greater Accra', 'Greater Accra'), ('Eastern', 'Eastern'), ('Western', 'Western'), ('Northern', 'Northern'), ('Ashanti', 'Ashanti')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Available'), (0, 'Unavailable')], null=True),
        ),
    ]
