# Generated by Django 3.2 on 2021-05-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0019_auto_20210531_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='acquisition_type',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, choices=[('Hostel', 'Hostel'), ('Self-Contained', 'Self-Contained'), ('Apartment', 'Apartment'), ('Flat', 'Flat')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='region',
            field=models.CharField(blank=True, choices=[('Greater Accra', 'Greater Accra'), ('Western', 'Western'), ('Eastern', 'Eastern'), ('Ashanti', 'Ashanti'), ('Northern', 'Northern')], max_length=200, null=True),
        ),
    ]
