# Generated by Django 3.2 on 2021-06-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0020_auto_20210531_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='lister_profile',
            field=models.FileField(blank=True, null=True, upload_to='lister_profile/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Flat', 'Flat'), ('Self-Contained', 'Self-Contained'), ('Hostel', 'Hostel')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='region',
            field=models.CharField(blank=True, choices=[('Greater Accra', 'Greater Accra'), ('Northern', 'Northern'), ('Ashanti', 'Ashanti'), ('Western', 'Western'), ('Eastern', 'Eastern')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Unavailable'), (1, 'Available')], null=True),
        ),
    ]
