# Generated by Django 3.2.4 on 2021-06-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0021_auto_20210601_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Flat', 'Flat'), ('Hostel', 'Hostel'), ('Self-Contained', 'Self-Contained')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='listed_by',
            field=models.CharField(blank=True, choices=[('Agency', 'Agency'), ('Agent', 'Agent'), ('Owner', 'Owner')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='region',
            field=models.CharField(blank=True, choices=[('Ashanti', 'Ashanti'), ('Eastern', 'Eastern'), ('Western', 'Western'), ('Northern', 'Northern'), ('Greater Accra', 'Greater Accra')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Available'), (0, 'Unavailable')], null=True),
        ),
    ]
