# Generated by Django 3.2 on 2021-05-31 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate', '0018_auto_20210531_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, choices=[('Eastern', 'Eastern'), ('Western', 'Western'), ('Ashanti', 'Ashanti'), ('Northern', 'Northern'), ('Greater Accra', 'Greater Accra')], max_length=250, null=True)),
                ('town', models.CharField(blank=True, max_length=250, null=True)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('unit', models.CharField(blank=True, choices=[('Plot', 'Plot'), ('Acres', 'Acres'), ('Sqft', 'Sqft')], max_length=250, null=True)),
                ('close_landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('lister', models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Agent', 'Agent'), ('Agency', 'Agency')], max_length=200, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('attachments', models.BooleanField(default=False)),
                ('land_type', models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Agriculture', 'Agriculture'), ('Commercial', 'Commercial')], max_length=250, null=True)),
                ('acquisition_type', models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=250, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('number_of_page_visits', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lands', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='land_images', to='estate.PropertyImage')),
                ('page_views', models.ManyToManyField(blank=True, related_name='land_views', to='estate.PageVisit')),
            ],
            options={
                'verbose_name': 'land',
                'verbose_name_plural': 'lands',
                'db_table': 'land',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='advert/')),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('duration', models.IntegerField(blank=True, choices=[(3, 'One Month'), (2, 'Two weeks'), (1, 'One week')], default=0, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('click_counts', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ads',
                'ordering': ['-created_at'],
            },
        ),
    ]
