# Generated by Django 3.2 on 2021-06-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_auto_20210601_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='duration',
            field=models.IntegerField(blank=True, choices=[(1, 'One week'), (2, 'Two weeks'), (3, 'One Month')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='acquisition_type',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='land_type',
            field=models.CharField(blank=True, choices=[('Commercial', 'Commercial'), ('Residential', 'Residential'), ('Agriculture', 'Agriculture')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='lister',
            field=models.CharField(blank=True, choices=[('Agency', 'Agency'), ('Agent', 'Agent'), ('Owner', 'Owner')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='region',
            field=models.CharField(blank=True, choices=[('Eastern', 'Eastern'), ('Western', 'Western'), ('Greater Accra', 'Greater Accra'), ('Ashanti', 'Ashanti'), ('Northern', 'Northern')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='unit',
            field=models.CharField(blank=True, choices=[('Plot', 'Plot'), ('Sqft', 'Sqft'), ('Acres', 'Acres')], max_length=250, null=True),
        ),
    ]
