# Generated by Django 3.2 on 2021-06-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_auto_20210601_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='duration',
            field=models.IntegerField(blank=True, choices=[(2, 'Two weeks'), (1, 'One week'), (3, 'One Month')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='acquisition_type',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='land_type',
            field=models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='lister',
            field=models.CharField(blank=True, choices=[('Agent', 'Agent'), ('Owner', 'Owner'), ('Agency', 'Agency')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='region',
            field=models.CharField(blank=True, choices=[('Greater Accra', 'Greater Accra'), ('Northern', 'Northern'), ('Ashanti', 'Ashanti'), ('Western', 'Western'), ('Eastern', 'Eastern')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Unavailable'), (1, 'Available')], null=True),
        ),
    ]
