# Generated by Django 3.2.4 on 2021-06-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0007_auto_20210601_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='page',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='duration',
            field=models.IntegerField(blank=True, choices=[(3, 'One Month'), (2, 'Two weeks'), (1, 'One week')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='land_type',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Agriculture', 'Agriculture')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='lister',
            field=models.CharField(blank=True, choices=[('Agency', 'Agency'), ('Agent', 'Agent'), ('Owner', 'Owner')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='region',
            field=models.CharField(blank=True, choices=[('Ashanti', 'Ashanti'), ('Eastern', 'Eastern'), ('Western', 'Western'), ('Northern', 'Northern'), ('Greater Accra', 'Greater Accra')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Available'), (0, 'Unavailable')], null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='unit',
            field=models.CharField(blank=True, choices=[('Acres', 'Acres'), ('Plot', 'Plot'), ('Sqft', 'Sqft')], max_length=250, null=True),
        ),
    ]
