# Generated by Django 3.2 on 2021-04-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
