# Generated by Django 3.2 on 2021-04-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('NU', 'Normal User'), ('AD', 'Admins')], max_length=200, null=True),
        ),
    ]
