# Generated by Django 3.2 on 2021-04-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210428_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rest_password',
            new_name='reset_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('AD', 'Admins'), ('NU', 'Normal User')], max_length=200, null=True),
        ),
    ]
