# Generated by Django 3.2 on 2021-05-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210510_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('NU', 'Normal User'), ('AD', 'Admins')], max_length=200, null=True),
        ),
    ]
